export const APPLICANT_PROFILE = "APPLICANT_PROFILE";
export const SET_APPLICANT_CURRENT_USER = "SET_APPLICANT_CURRENT_USER";
export const GET_ERRORS = "GET_ERRORS";
export const APPLICANT_SIGNUP_ERROR_REDUCER = "APPLICANT_SIGNUP_ERROR_REDUCER";
export const MESSAGE_LIST = "MESSAGE_LIST";
export const GET_MESSAGE_ERRORS = "MESSAGE_LIST";
export const MESSAGE_DETAILS_BY_ID = "MESSAGE_DETAILS_BY_ID";
export const MESSAGE_VIEW = "MESSAGE_VIEW";
