export const APPLICANT_PROFILE = 'APPLICANT_PROFILE';
export const RECRUITER_PROFILE = 'RECRUITER_PROFILE';
export const SET_APPLICANT_CURRENT_USER = 'SET_APPLICANT_CURRENT_USER';
export const SET_RECRUITER_CURRENT_USER = 'SET_RECRUITER_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const RECRUITER_GET_ERRORS = 'RECRUITER_GET_ERRORS';
export const APPLICANT_SIGNUP_ERROR_REDUCER = 'APPLICANT_SIGNUP_ERROR_REDUCER';
export const RECRUITER_SIGNUP_ERROR_REDUCER = 'RECRUITER_SIGNUP_ERROR_REDUCER';