export const APPLICANT_PROFILE = 'APPLICANT_PROFILE';
export const SET_APPLICANT_CURRENT_USER = 'SET_APPLICANT_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const APPLICANT_SIGNUP_ERROR_REDUCER = 'APPLICANT_SIGNUP_ERROR_REDUCER';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';
export const ADD_EXPERIENCE = 'ADD_EXPERIENCE';